### ISSUE TITLE
Wildcard when filtering

### ISSUE THREAD

**Issue by alrapal** [ItJustWorksBetterTM/EiffelVis#36] opened 2022-11-01 14:12 UTC
## Description 
As a user, I want to be able to use wildcards when filtering so that I can filter with more ease

## Acceptance Criteria
- [ ] Performance should not be downgraded 
- [ ] Code should be commented
- [ ] Filtering options Type, Host, Tag, Source should support partial search (giving incomplete words returns all node matching the partial search
- [ ] Feedback should be given when filter returns nothing

**Comment by RuthgerD** [comment] 2022-11-02 11:38
duplicate of #35

**Comment by alrapal** [comment] 2022-11-02 16:54
> duplicate of #35

Thanks! Copy pasting from Trello did not work as expected here haha! I changed the description to match what it was supposed to be

**Comment by RuthgerD** [comment] 2022-11-02 17:39
Alright I think this one needs a bit more detail as to what defines partial search, as it can range from regex to just `String::starts_with`.

relevant place to change these things is [here](https://github.com/ItJustWorksTM/EiffelVis/blob/master/backend/crates/eiffelvis_core/src/domain/user_queries.rs#L151).

Using regex in this hot loop is unacceptable already, something like [`String::contains`](https://doc.rust-lang.org/std/string/struct.String.html#method.contains) is probably the best bet.

**Comment by gusaxtcha** [comment] 2022-11-03 09:29
> RuthgerD

Hi Ruthger,

Adding the details you've mentioned is more related to implementation then acceptance criteria. 
I have been working on this issue and have come to the same conclusion as the suggestion you've made. I already have a working prototype locally and will push it soon.

**Closed** 2022-11-11 07:49 UTC
Labels: User story, Filter, Sprint4
